/*
 * @Author: Punal Manalan
 * @Description: Proxy Server Plugin.
 * @Date: 22/11/2025
 */

#pragma once

#include "CoreMinimal.h"
#include "Subsystems/WorldSubsystem.h"
#include "CPP_LoginHandler.h"
#include "CPP_STRUCT__ProxyServer.h"
#include "CPP_LoginManagerSubsystem.generated.h"

UCLASS(Config = Game) // Punal Manalan, NOTE: Specifying Unreal Engine to look for this Config in DefaultGame.ini
class P_PROXYSERVER_API UCPP_LoginManagerSubsystem : public UWorldSubsystem, public ICPP_LoginHandler
{
    GENERATED_BODY()

public:
    bool EnableGloablEncryptionValidation = true;
    bool EnableLocalEncryptionValidation = true;

    // Punal Manalan, NOTE: These store the FILENAMES (Loaded from Config)
    UPROPERTY(Config)
    FString GlobalPrivateKeyFilename = "Secrets/GlobalKey.pem";

    UPROPERTY(Config)
    FString GlobalPublicKeyFilename = "Secrets/GlobalKey.pem";

    UPROPERTY(Config)
    int JoinSessionToken_Expiry_Seconds = 360; // Punal Manalan, Default: 6 Minutes

    // Punal Manalan, NOTE: These are Packaged with the Server Build, as Part of Config File.
    FString Server_Global_PrivateKeyPEM = "";
    FString Server_Global_PublicKeyPEM = "";

    // Punal Manalan, NOTE: These are Either Generated by the Server at Runtime or Received from an External Source(Such as Backend).
    FString Server_Local_PrivateKeyPEM = "";
    FString Server_Local_PublicKeyPEM = "";

    bool bIsServerLocked = false;
    FString Backend_Server_URL = TEXT("http://localhost:8080/api/");

    /*
     * Punal Manalan, NOTE: These are Role Lists and Maps used for Login Validation
     * Note: If a Player is "Banned" and "TemporaryTimeout", They should not even be allowed to Enter the Server.
     * but the Join Session Token validation will also catch this(the Backend Server should actually Handle it).
     * because the Role List is Set from the Backend Server Response when the Player Joins.
     */
    TArray<FString> AllowedRole_List = {"Admin", "Moderator", "VIP", "Regular"}; // Roles allowed to join the server.
    TArray<FString> RestrictedRole_List = {"Banned", "TemporaryTimeout"};        // Roles Not allowed to join the server.
    TMap<FString, FPlayerData> PlayerID_SessionData_Map;                         // Map of PlayerID to PlayerData (could include session info, etc.)

public:
    virtual bool ShouldCreateSubsystem(UObject *Outer) const override;

    void GenerateNewRSAKeyPair(int32 KeySizeInBits = 2048, bool bIsGlobalKey = false);

    // --- Interface Implementation Start ---

    virtual bool InitializeLoginHandler_Implementation() override;

    virtual bool LoadGlobalKeyFromFile_Implementation(const FString &RelativePath, FString &OutKeyContent) override;

    virtual bool SendAPIRequestToBackendServer_Implementation(const FString &Send_Payload, const FOnSentAPIResponse &ResponseDelegate) override;

    virtual bool HandleAPIResponseFromBackendServer_Implementation(const FString &Sent_Payload, const FString &Response_Payload, FString &Error) override;

    virtual bool HandleAPIFromBackendServer_Implementation(const FString &Received_Payload) override;

    virtual bool ValidatePlayerLogin_Implementation(const FString &Options, const FString &Address, const FUniqueNetIdRepl &UniqueId, FString &OutErrorMessage) override;

    virtual void OnPlayerPostLogin_Implementation(APlayerController *NewPlayer) override;
    // --- Interface Implementation End ---

    // Getters / Setters exposed to Blueprints and C++
    UFUNCTION(BlueprintCallable, Category = "Punal|Login Manager")
    bool IsServerLocked() const;

    UFUNCTION(BlueprintCallable, Category = "Punal|Login Manager")
    void SetServerLocked(bool bLocked);

    UFUNCTION(BlueprintCallable, Category = "Punal|Login Manager")
    FString GetBackendServerURL() const;

    UFUNCTION(BlueprintCallable, Category = "Punal|Login Manager")
    void SetBackendServerURL(const FString &URL);

    UFUNCTION(BlueprintCallable, Category = "Punal|Login Manager")
    TArray<FString> GetAllowedRoleList() const;

    UFUNCTION(BlueprintCallable, Category = "Punal|Login Manager")
    void SetAllowedRoleList(const TArray<FString> &NewList);

    UFUNCTION(BlueprintCallable, Category = "Punal|Login Manager")
    TArray<FString> GetBannedRoleList() const;

    UFUNCTION(BlueprintCallable, Category = "Punal|Login Manager")
    void SetBannedRoleList(const TArray<FString> &NewList);

    UFUNCTION(BlueprintCallable, Category = "Punal|Login Manager")
    TMap<FString, FPlayerData> GetPlayerID_SessionData_Map() const;

    UFUNCTION(BlueprintCallable, Category = "Punal|Login Manager")
    void SetPlayerID_SessionData_Map(const TMap<FString, FPlayerData> &NewMap);

    // Server key getters/setters
    UFUNCTION(BlueprintCallable, Category = "Punal|Login Manager|Crypto")
    FString GetServer_Global_PrivateKeyPEM() const;

    UFUNCTION(BlueprintCallable, Category = "Punal|Login Manager|Crypto")
    void SetServer_Global_PrivateKeyPEM(const FString &NewPrivateKeyPEM);

    UFUNCTION(BlueprintCallable, Category = "Punal|Login Manager|Crypto")
    FString GetServer_Global_PublicKeyPEM() const;

    UFUNCTION(BlueprintCallable, Category = "Punal|Login Manager|Crypto")
    void SetServer_Global_PublicKeyPEM(const FString &NewPublicKeyPEM);
};
